# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

references:
  node_modules_key: &node_modules_key redemptions-dependencies-v4-{{ checksum "package.json" }}-{{ checksum "app/package.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *node_modules_key

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout
      - run: #STABLE
          name: Install Chromedriver latest version
          command: |
            sudo apt-get update
            sudo apt-get install lsb-release libappindicator3-1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb

      - run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm i

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: getChromeVersion
          command: google-chrome --version

      - run:
          name: getChromePath
          command: whereis google-chrome

      - save_cache:
          paths:
            - node_modules
            - app/node_modules
          key: *node_modules_key

      - run: sudo apt install rsync

      - run:
          name: Visual Tests
          command: npm run test:e2e

  coverage:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      - *restore_node_modules

      - run:
          name: Run tests
          command: npm run coverage

      - run:
          name: Report Coverage
          command: npm run coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - coverage:
          requires:
            - build
