# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: redemptions-dependencies1-{{ checksum "package.json" }}

      - run: sudo apt install rsync

      - run:
          name: Run tests
          command: npm run coverage

      - run:
          name: Visual Tests
          command: npm run test:e2e

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
