# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

references:
  node_modules_key: &node_modules_key redemptions-dependencies-v15-{{ checksum "package.json" }}-{{ checksum "app/package.json" }}

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - *node_modules_key

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: getChromeVersion
          command: google-chrome --version

      - run:
          name: getChromePath
          command: whereis google-chrome

      - run: sudo apt install rsync

      - run:
          name: Visual Tests
          command: npm run test:e2e

      - save_cache:
          paths:
            - node_modules
            - app/node_modules
          key: *node_modules_key

  coverage:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - *restore_node_modules

      - run:
          name: Run tests
          command: npm run coverage

      - run:
          name: Report Coverage
          command: npm run coveralls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - coverage:
          requires:
            - build
